apiVersion: v1
kind: Service
metadata:
  name: kube-registry
  namespace: kube-system
  labels:
    k8s-app: kube-registry
    # kubernetes.io/cluster-service: "true"
    kubernetes.io/name: "KubeRegistry"
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: 'http'
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: '443,5000'
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: 'arn:aws:acm:us-east-1:366543340701:certificate/0a216d9f-ae74-4681-bb78-03adb4ace420'
spec:
  type: LoadBalancer
  selector:
    k8s-app: kube-registry
  ports:
  - name: registry
    port: 5000
    protocol: TCP
  - name: https
    port: 443
    protocol: TCP
    targetPort: 5000
  - name: http
    port: 80
    protocol: TCP
    targetPort: 5000