apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kube-registry
  namespace: kube-system
  labels:
    k8s-app: kube-registry
    version: v0
spec:
  replicas: 2
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        k8s-app: kube-registry
        version: v0
    spec:
      containers:
      - name: registry
        image: registry:2.5.0
        resources:
          limits:
            cpu: 100m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 256Mi
        env:
        - name: SETTINGS_FLAVOR
          value: s3
        - name: AWS_BUCKET
          value:
        - name: STORAGE_PATH
          value: /registry
        - name: AWS_KEY
          value:
        - name: AWS_SECRET
          value:
        - name: SEARCH_BACKEND
          value: sqlalchemy
        - name: REGISTRY_HTTP_ADDR
          value: :5000
        - name: REGISTRY_AUTH
          value: htpasswd
        - name: REGISTRY_AUTH_HTPASSWD_REALM
          value: "Registry Realm"
        - name: REGISTRY_AUTH_HTPASSWD_PATH
          value: /auth/htpasswd
        volumeMounts:
        - name: auth-dir
          mountPath: /auth
        ports:
        - containerPort: 5000
          name: registry
          protocol: TCP
      volumes:
      - name: auth-dir
        secret:
          secretName: registry-auth-secret