apiVersion: v1
kind: PersistentVolume
metadata:
  name: kube-registry-data-disk
  namespace: kube-system
  labels:
    name: kube-registry-data-disk
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  awsElasticBlockStore:
    volumeID: vol-2bc9b18e
    fsType: ext4